---
title: "Oh learner, where are thou?"
author: "Learn to Code R seminar 1"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: yeti
    highlight: kate
---

----

```{r setup, include=FALSE}
# set code -> html rendering behaviour
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

## ðŸ‘‹ Welcome! So glad you could make it! ðŸ‘‹

This is a short vignette to whet your appetite for R. I want to give you a taste of how surprisingly easy it can be to produce  professional-looking 'data products' that will instantly put you ahead of the pack. 

Maps are the one of the most common visualizations but are also one of the most challenging to create.  <!-- Anyone here created a map before? What was your experience or result like? --> Simple maps are dead easy in R because we have awesome libraries to do take care of 'the bullshit'^[1] for us. Let's make a map of where we are all joining the seminar from today ðŸ“ðŸ—ºðŸ“

---

#### Do this to start:

  - Go to Google maps > find your area (not exact location, for privacy)
  - Click drop a pin & copy the coordinates from the card at the bottom of the map.
  - Fill in your coordinates here: https://forms.gle/1XoxfkhGLxqEHik9A


----

### Data from our Google form

Great workflow for simple data collection: Gform -> Gsheet -> R


```{r}
# load packages
library(tidyverse)
library(leaflet)
library(googlesheets4)
#+
# read data from google sheets
coords <-
  googlesheets4::read_sheet(
    "https://docs.google.com/spreadsheets/d/1EpByX-P6ou74xqcTF4gX388g-zbMEHPyHsBZADyMhsU/edit?usp=sharing"
  ) |>
  # create html labels for the map
  dplyr::mutate(label = str_glue(
    'Responded <b>{Timestamp}</b><br>
     Lat ~ <b>{round(latitude, 2)}</b><br>
     Lng ~ <b>{round(longitude, 2)}</b>
    '))
```


```{r}
# preview data
coords |>
  dplyr::mutate(
    across(where(is.numeric), ~round(.x, 1))
  ) |>
  head(5)
```


### Map

```{r fig.align='center'}
# use the leaflet package to create our map in layers
leaflet::leaflet() |>
  leaflet::addProviderTiles(providers$CartoDB.Positron) |>
  # add markers based on survey data
  leaflet::addMarkers(
    data = coords,
    lng = ~longitude,
    lat = ~latitude,
    popup = ~label,
    label = ~label
    )
```

<br>


### Render script to html

Render this script to an html file to html with `rmarkdown::render`.

`rmarkdown::render('R/leaflet_map.R')`

-----

<br>

-----

\footnotes

[1] The bullshit of dealing with millions of bugs when you aren't a software engineer but you are rolling your own geoinformatics platform.




