---
title: "**ðŸ—ºðŸ“ Learner MapðŸ“ðŸ—º**"
author: "Jason Moggridge"
date: "`r Sys.Date()`"
output: html_document
---

----

## ðŸ‘‹ Welcome! ðŸ‘‹

This is a short vignette to show you how easy it can be to create impressive figures and documents with R and Rmarkdown.

---

#### Do this to start

- Go to Google maps > find your area (not exact location, for privacy)
- Click drop a pin & copy the coordinates from the card at the bottom of the map.
- Fill in your coordinates here: https://forms.gle/1XoxfkhGLxqEHik9A


----

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```


```{r}
# install.packages(c('leaflet', 'googlesheets4'))
# load packages
library(tidyverse)
library(leaflet)
library(googlesheets4)
```



## Google API

You'll need a google account to access any google API, and even if you have a google account, you still might need to setup an authorization token. Visit https://gargle.r-lib.org/index.html for more info on how to do this configuration, or just take a shot at letting it configure automatically by entering this into your R console:   
`options(gargle_oauth_email = TRUE)`

```{r}
coords <-
  # from this spreadsheet url...
  "https://docs.google.com/spreadsheets/d/1EpByX-P6ou74xqcTF4gX388g-zbMEHPyHsBZADyMhsU/edit?usp=sharing" |> 
  # read data...
  googlesheets4::read_sheet()

# preview data
coords |> head()
```

----

Now that our data is loaded, let's create some html-formatted text with  details to show as popups for each marker.

```{r}
# mutate() creates a new column that we've called 'popup'
# str_glue() inserts our data variables into a text template,
# variables are referenced by name in code expressions wrapped with {}
coords <- coords |>
  mutate(popup = str_glue(
    'Responded at <b>{Timestamp}</b><br>
     Lat ~ <b>{round(latitude, 2)}</b><br>
     Lng ~ <b>{round(longitude, 2)}</b>') |> 
      as.character()
    )

# check the new column we created
coords |> head()
```

---

### Leaflet
 
We'll use the Leaflet package to build our map in layers: canvas -> background -> data markers.

<!-- this is html that wont show up in the final document -->
<style>
.html-widget {
    margin: auto;
}
</style>

```{r fig.height=8, fig.width=8}
# blank map
leaflet::leaflet() |>
  # add the base layer style
  leaflet::addProviderTiles(
    providers$CartoDB.Positron,
    options = providerTileOptions(noWrap = TRUE)
  ) |>
  # add markers based on survey data
  leaflet::addMarkers(
    data = coords,
    lng = ~longitude,
    lat = ~latitude,
    label = ~str_glue('{latitude}, {longitude}'),
    popup = ~popup
    ) |>
  addMiniMap(
    tiles = providers$OpenStreetMap,
    toggleDisplay = TRUE
    )
```

-----

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


