#-------------------------------------------------------#
#' Project: Learn to code - seminar 2
#' Script: Starwars | dplyr and ggplot2
#-------------------------------------------------------#





##----------------------------------------------##
## *regex*                                    ----
##----------------------------------------------##

#' What if we want to *match a pattern* in text data?
#' Use `str_*` functions from `stringr`

#' Patterns are regular expressions, *regex*
#' Here, ` ^ `` indicates the start of the string
#' [A-Za-z]+ matches any block of letters

str_detect('Darth Vader', '^Darth [A-Za-z]+')
str_detect('Master Darth Vader', '^Darth [A-Za-z]+')


# find all dudes with the first name 'Darth'
# test for the pattern 'Darth <something>'
darths <-
  starwars |>
  filter(str_detect(name, '^Darth [A-Za-z]+')) |>
  select(name) |>
  print()

# rename to garth and lowercase their names
garths <-
  darths |>
  mutate(name = name |>
           str_replace_all('D', 'G') |>
           str_to_lower()
  ) |>
  print()

rm(darths, garths)

#' learn more about `stringr` and *regex* here
#' https://stringr.tidyverse.org/articles/regular-expressions.html

# super common uses - find emails, phone #, dates...
string <- "123-456-9876, 11 Foobar St., baz-1@gmail.com"
email_regex <- '[A-z0-9_-]+@[A-z0-9]+\\...(.)?'
phone_regex <- '[:digit:]{3}.[:digit:]{3}.[:digit:]{4}'

# extract text matching the pattern for email
str_extract(string = string,
            pattern = email_regex)

# replace text matching the pattern for phone
str_replace(string = string,
            pattern = phone_regex,
            replacement = '<phone number suppressed>')



rm(email_regex, phone_regex, string)









##----------------------------------------------##
## *string interpolation*                                    ----
##----------------------------------------------##

#' *string interpolation* with `str_glue` and {}

# some data generated by our code
value <- rnorm(mean = 95, sd = 1, n = 1) |> round(1)

# insert result into a text template
str_glue(
  'String interpolation is a handy tool that I use in {value}% of my reports.')


rm(value)















##----------------------------------------------##
## more dplyr                                    ----
##----------------------------------------------##

#' *super handy*

#' `distinct` get unique combination of (input variables)
starwars |> distinct(species, sex)

#' stack tables with `bind_rows`
#' remove duplicates with `distinct`

# eg. duplicate data; remove any duplicates (cancels out)
bind_rows(starwars, starwars) |> distinct()

# nest / unnest lists
# open nested data up over more rows/cols
# fold up data into nested lists / tibbles

# eg. list the cast of each film in a nested column
films <-
  starwars |>
  select(name, films) |>
  unnest(films) |>
  nest(cast = name) |>
  print()

# which ships are flown by the most characters?
ships <-
  starwars |>
  select(name, starships) |>
  unnest(cols = c(starships)) |>  # keep_empty = T
  group_nest(starships, .key = 'pilots') |>
  mutate(piloted_by = map_dbl(pilots, ~nrow(.x))) |>
  arrange(desc(piloted_by)) |>
  print()

# join data
ships_births <-
  starwars |>
  select(name, birth_year) |>
  right_join(ships |> unnest(pilots), by = 'name') |>
  relocate(name, starships)

ships_births |>
  ggplot(aes(birth_year, starships)) +
  geom_point(alpha = 0.7)









##----------------------------------------------##
## *across*                                    ----
##----------------------------------------------##

#' `across` allows us to repeat a mutate/summarise
#' on multiple columns

# modify all character strings to be uppercase
starwars |>
  mutate(
    across(
      .cols = where(is.character), # do all these cols
      .fns = ~str_to_upper(.x)     # with this function
    )
  )

# convert cols matching name pattern to factors
starwars <- starwars |>
  mutate(
    across(matches('color|sex|gend|home|spec'),
           as_factor
    ))

starwars |>
  select(-where(is.list)) |>
  base::summary()




##----------------------------------------------##
## Summary table                           ----
##----------------------------------------------##

## Let's Make a Summary Table
cohort <-
  starwars |>
  group_by(species) |>
  mutate(n = n()) |>
  filter(n > 2, !is.na(species)) |>
  glimpse()

cohort |> count(species)

# use *across* to compute a numeric summary for any numeric variables for the table 1.

tbl1 <-
  cohort |>
  summarise(
    across(
      .cols = where(is.numeric),
      .fns = list(
        'mean' = ~mean(.x, na.rm = T) |> round(),
        'sd' = ~sd(.x, na.rm = T) |> round()
      ),
      .names = "{.col}_{.fn}",
    ),
    N = n() |> as.character(),
  ) |>
  transmute(
    species,
    N,
    Height = str_glue('{height_mean} ± {height_sd}'),
    Mass = str_glue('{mass_mean} ± {mass_sd}'),
  ) |>
  print()


library(gt)

tbl1 |>
  # transpose data with pivots s.t. species are columns
  pivot_longer(-species) |>
  pivot_wider(names_from = species, values_from = value) |>
  # present as html table
  gt::gt(rowname_col = 'name') |>
  gt::tab_spanner('Species', c(Droid, Gungan, Human)) |>
  gt::tab_header(title = 'Table 1. Starwars cohort')







##----------------------------------------------##
## More dplyr                                 ----
##----------------------------------------------##

#' `relocate` columns to the left (- to the right)
#' helpful when you want to see the one you're working on
starwars |> relocate(starships)

#' `rename` columns: new_name = old_name
starwars |> rename(height_cm = height)
starwars |> rename_with(~str_remove(.x, '_color'))

#' `slice_*` functions get a subset of rows (by various criteria)
starwars |> slice_min(birth_year) |> glimpse()
starwars |> slice_max(birth_year) |> glimpse()

#' eg. get a random sample of observations
starwars |> slice_sample(n = 5)






















